<?xml version="1.0" encoding="UTF-8"?>
<testsuite time='0.000265' skipped='0' failures='0' errors='0' name="NodeTest" assertions='5' tests='4' timestamp="2024-10-29T09:02:01+00:00">
  <testcase time='0.000087' file="test/id58_test_base.rb" name="test_\nid=&#39;3q1Ps3&#39;\nos=Alpine\n&#39;image_names are retrieved from the node via docker image ls call&#39;" assertions='1'>
  </testcase>
  <testcase time='0.000061' file="test/id58_test_base.rb" name="test_\nid=&#39;3q1Ps4&#39;\nos=Alpine\n&#39;&lt;none&gt;:&lt;none&gt; image_names are filtered out&#39;" assertions='1'>
  </testcase>
  <testcase time='0.000059' file="test/id58_test_base.rb" name="test_\nid=&#39;3q1Ps5&#39;\nos=Alpine\n&#39;image_names populate puller in config.ru&#39;" assertions='1'>
  </testcase>
  <testcase time='0.000057' file="test/id58_test_base.rb" name="test_\nid=&#39;3q1Ps6&#39;\nos=Alpine\n&#39;when docker image ls call fails exception is raised&#39;" assertions='2'>
  </testcase>
</testsuite>
